package @PACKAGE@.configuration

import net.minecraftforge.common.Configuration
import cpw.mods.fml.common.FMLCommonHandler

/*
 * Config
 * @PACKAGE@.configuration
 *
 * Generated by ScalaForge Skeleton at @DATE@
 */

/**
 * Configuration support strut
 */
object Config {

    //=== Defaults ==================================
    // TODO: Store vars for your mod here

    //=== Functions =================================
    def loadConfig(cfg:Configuration) {
        cfg.load()

        // TODO: Load configuration here e.g.
        // varNameFromDefaults = cfg.getBlock("blockName", varNameFromDefaults).getInt

        cfg.save()
    }

}
