package @PACKAGE@.lib

/*
 * Constants
 * @PACKAGE@.lib
 *
 * Generated by ScalaForge Skeleton at @DATE@
 */

/**
 * Constants for use throughout.
 */
object Constants {

    final val modId = "@MODNAME@"
    final val modName = "@MODID@"
    final val version = "@VERSION@"
    final val modDeps = ""
    final val modLang = "scala"

}
