package @PACKAGE@.lib

import java.util.logging.Logger

/*
 * Repo
 * @PACKAGE@.lib
 *
 * Generated by ScalaForge Skeleton at @DATE@
 */

/**
 * Object store
 */
object Repo {

    val logger = Logger.getLogger("@MODNAME@")

    // TODO: Add objects shared for the whole mod here

}
