package @PACKAGE@

import cpw.mods.fml.common.Mod
import cpw.mods.fml.common.network.NetworkMod
import cpw.mods.fml.common.Mod.{PostInit, Init, PreInit}
import cpw.mods.fml.common.event.{FMLPostInitializationEvent, FMLInitializationEvent, FMLPreInitializationEvent}
import net.minecraftforge.common.Configuration
import @PACKAGE@.configuration.Config
import @PACKAGE@.lib.Constants._

/*
 * @MODNAME@
 * @PACKAGE@
 *
 * Generated by ScalaForge Skeleton at @DATE@
 */

/**
 * @MODNAME@ FML container
 */
@Mod(modid = modId,
    name = modName,
    version = version,
    dependencies = modDeps,
    modLanguage = modLang)
@NetworkMod(clientSideRequired = true,
    serverSideRequired = false)
object @MODID@ {

    /**
     * FML Preinit
     *
     * Loads configuration
     *
     * @param event FML event
     */
    @PreInit
    def preInit(event:FMLPreInitializationEvent) {
        Config.loadConfig(new Configuration(event.getSuggestedConfigurationFile))
    }

    /**
     * FML Init
     *
     * @param event FML event
     */
    @Init
    def init(event:FMLInitializationEvent) {
        // TODO: GameRegistry-related setup
    }

    /**
     * FML Postinit
     *
     * @param event FML event
     */
    @PostInit
    def postInit(event:FMLPostInitializationEvent) {

    }

}
